
### errors/warnings done

#
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory


#
pip install git+https://github.com/divamgupta/image-segmentation-keras

: out
Successfully built keras-segmentation
Installing collected packages: cycler, python-dateutil, kiwisolver, pyparsing, matplotlib, Pillow, imageio, PyWavelets, decorator, networkx, scikit-image, Shapely, opencv-python-headless, imgaug, tqdm, keras-segmentation
Successfully installed Pillow-6.2.1 PyWavelets-1.1.1 Shapely-1.6.4.post2 cycler-0.10.0 decorator-4.4.1 imageio-2.6.1 imgaug-0.3.0 keras-segmentation-0.3.0 kiwisolver-1.1.0 matplotlib-3.1.1 networkx-2.4 opencv-python-headless-4.1.1.26 pyparsing-2.4.5 python-dateutil-2.8.1 scikit-image-0.16.2 tqdm-4.38.0


# tensorflow:latest-gpu-py3 / TF2.0
2019-11-18 21:43:33.529490: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7630 MB memory) -> physical GPU (device: 0, name: Quadro P4000, pci bus id: 0000:00:05.0, compute capability: 6.1)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.6/dist-packages/keras_segmentation/pretrained.py", line 81, in pspnet_101_voc12
    return model_from_checkpoint_path(model_config, latest_weights)
  File "/usr/local/lib/python3.6/dist-packages/keras_segmentation/pretrained.py", line 11, in model_from_checkpoint_path
    input_width=model_config['input_width'])
  File "/usr/local/lib/python3.6/dist-packages/keras_segmentation/models/pspnet.py", line 123, in pspnet_101
    input_shape=input_shape)
  File "/usr/local/lib/python3.6/dist-packages/keras_segmentation/models/_pspnet_2.py", line 267, in _build_pspnet
    psp = build_pyramid_pooling_module(res, input_shape)
  File "/usr/local/lib/python3.6/dist-packages/keras_segmentation/models/_pspnet_2.py", line 243, in build_pyramid_pooling_module
    interp_block1 = interp_block(res, 1, feature_map_size, input_shape)
  File "/usr/local/lib/python3.6/dist-packages/keras_segmentation/models/_pspnet_2.py", line 233, in interp_block
    prev_layer = Interp(feature_map_shape)(prev_layer)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras_segmentation/models/_pspnet_2.py", line 37, in call
    resized = tf.image.resize_images(inputs, [new_height, new_width],
AttributeError: module 'tensorflow_core._api.v2.image' has no attribute 'resize_images'

>>>        resized = tf.image.resize_images(inputs, [new_height, new_width], align_corners=True)



